FROM fauria/vsftpd:latest

COPY test1.xml /home/bob/test1.xml
COPY test2.xml /home/bob/test2.xml
COPY test3.xml /home/bob/test3.xml

COPY test1.xml /home/bob/test4.xml
COPY test2.xml /home/bob/test5.xml
COPY test3.xml /home/bob/test6.xml

COPY test1.xml /home/bob/test7.xml
COPY test2.xml /home/bob/test8.xml
COPY test3.xml /home/bob/test9.xml
